version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestGitCommitFlowsProject
  gitServerName: pooja
  gitUrl: https://github.com/PoojaAnandGit
  gitUsername: PoojaAnandGit
  gitBranch: main
