version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestGitCommitFlowsProject
  gitServerName: pooja
  gitUrl: https://github.com/PoojaAnandGit
  gitUsername: PoojaAnandGit
  gitBranch: main
services:
- serviceName: project.testgitcommitflows.integrations:e12
  packages:
  - name: TestGitCommitFlowsProject
    version: "1.0"
- serviceName: pub.client:http
  packages:
  - name: WmPublic
    version: 11.1.0.0.2006
